#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import print_function

import datetime
from itertools import chain, repeat
from subprocess import call
import sys
import time

import RPi.GPIO as gpio

try:
    # Set Up:
    gpio.setmode(gpio.BCM)
    gpio.setup(23, gpio.OUT)

    while True:
        # Turn the LED on and off:
        gpio.output(23, True)
        time.sleep(1)
        gpio.output(23, False)
        time.sleep(1)
except KeyboardInterrupt:
    pass
finally:
    gpio.cleanup()

