#!/usr/bin/env python
# -*- coding: utf-8 -*-

from subprocess import call

import RPi.GPIO as gpio


try:
    gpio.setmode(gpio.BCM)
    gpio.setup(18, gpio.IN, pull_up_down=gpio.PUD_UP)

    while True:
        input_state = gpio.input(18)
        if input_state == False:
            call("aplay airhorn.wav", shell=True)
except KeyboardInterrupt:
    pass
finally:
    gpio.cleanup()

