#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import print_function

import datetime
from itertools import chain, repeat
from subprocess import call
import sys
import time

from hot import *


NUMBER_WORDS=["one", "two", "three", "four", "five", "six", "seven", "eight","nine", 
       "ten", "eleven", "twelve", "thirteen", "fourteen", "quarter", "sixteen",
       "seventeen", "eighteen", "nineteen", "twenty", "twenty one", 
       "twenty two", "twenty three", "twenty four", "twenty five", 
       "twenty six", "twenty seven", "twenty eight", "twenty nine", "half"]
 

def speak(message):
    call(["/usr/bin/espeak", message])


def time_text():
    dd=datetime.datetime.now()
    hrs = dd.hour
    mins = dd.minute
    header="It is "
    msg=""
    if (hrs >12):
        hrs=hrs-12
    if (mins == 0):
        hr = NUMBER_WORDS[hrs-1]
        msg=header + hr + " o'clock."
    elif (mins < 31):      
           hr = NUMBER_WORDS[hrs-1]
           mn = NUMBER_WORDS[mins-1]
           msg = header + mn + " past " + hr + "."
    else:
        hr = NUMBER_WORDS[hrs]
        mn =NUMBER_WORDS[(60 - mins-1)]
        msg = header + mn + " to " + hr + "."
    return msg


try:
    with setup():
        while True:
            if button_pressed():
                set_led(True)
                time.sleep(0.5)
                speak(time_text())
                set_led(False)
            time.sleep(0.2)
except KeyboardInterrupt:
    pass
